# Generated by Django 3.2.8 on 2021-11-06 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UserBasic',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('user_password', models.CharField(max_length=255)),
                ('is_superuser', models.IntegerField()),
                ('is_teacher', models.IntegerField()),
            ],
            options={
                'db_table': 'user_basic',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UserMessage',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='mainpage.userbasic')),
                ('user_message', models.CharField(blank=True, max_length=255, null=True)),
                ('user_readornot', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'user_message',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UserPermission',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='mainpage.userbasic')),
                ('name', models.CharField(max_length=255)),
                ('content', models.IntegerField()),
                ('codename', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'user_permission',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UserStudentProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='mainpage.userbasic')),
                ('user_nickname', models.CharField(blank=True, max_length=255, null=True)),
                ('user_email', models.CharField(max_length=255)),
                ('user_phonenumber', models.IntegerField(blank=True, null=True)),
                ('user_sex', models.CharField(blank=True, max_length=10, null=True)),
                ('user_age', models.IntegerField(blank=True, null=True)),
                ('user_city', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'user_student_profile',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CourseBasic',
            fields=[
                ('course_id', models.IntegerField(primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=255)),
                ('course_type', models.IntegerField()),
                ('course_teacher', models.CharField(max_length=255)),
                ('course_city', models.CharField(max_length=255)),
                ('course_deadline', models.DateTimeField()),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mainpage.userbasic')),
            ],
            options={
                'db_table': 'course_basic',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UserTeacherProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='mainpage.userbasic')),
                ('user_nickname', models.CharField(blank=True, max_length=255, null=True)),
                ('user_email', models.CharField(max_length=255)),
                ('user_phonenumber', models.IntegerField(blank=True, null=True)),
                ('user_sex', models.CharField(blank=True, max_length=10, null=True)),
                ('user_age', models.IntegerField(blank=True, null=True)),
                ('user_city', models.CharField(max_length=255)),
                ('user_subjecttype', models.IntegerField()),
            ],
            options={
                'db_table': 'user_teacher_profile',
                'managed': True,
                'unique_together': {('user', 'user_subjecttype')},
            },
        ),
    ]
