# Generated by Django 3.2.8 on 2021-11-04 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursebasic',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='userbasic',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='usermessage',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='userpermission',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='userstudentprofile',
            options={'managed': True},
        ),
    ]
