# Generated by Django 3.2.8 on 2021-11-04 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_auto_20211104_2212'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursebasic',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='student.userbasic'),
        ),
    ]
