# Generated by Django 3.2.8 on 2021-11-06 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_coursebasic_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermessage',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userpermission',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userstudentprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='CourseBasic',
        ),
        migrations.DeleteModel(
            name='UserBasic',
        ),
        migrations.DeleteModel(
            name='UserMessage',
        ),
        migrations.DeleteModel(
            name='UserPermission',
        ),
        migrations.DeleteModel(
            name='UserStudentProfile',
        ),
    ]
